// Generated by Wrangler by running `wrangler types`

// Cloudflare Workers types
declare global {
	interface Request extends globalThis.Request {}
	interface Response extends globalThis.Response {}
	interface URL extends globalThis.URL {}
	
	type ExportedHandler<Env = any> = {
		fetch?: (request: Request, env: Env, ctx: ExecutionContext) => Response | Promise<Response>;
		scheduled?: (event: ScheduledEvent, env: Env, ctx: ExecutionContext) => void | Promise<void>;
	};
}

interface Env {
	DB: D1Database;
	CONGRESS_API_KEY?: string;
}
