-- Migration number: 0015 - Create congressional districts
-- This creates all districts for the 119th Congress

INSERT INTO districts (state_code, district_number, name) VALUES
-- Alabama districts
('AL', 1, 'Alabama 1st District'),
('AL', 2, 'Alabama 2nd District'),
('AL', 3, 'Alabama 3rd District'),
('AL', 4, 'Alabama 4th District'),
('AL', 5, 'Alabama 5th District'),
('AL', 6, 'Alabama 6th District'),
('AL', 7, 'Alabama 7th District'),
-- Alaska
('AK', 0, 'Alaska At-Large'),
-- Arizona
('AZ', 1, 'Arizona 1st District'),
('AZ', 2, 'Arizona 2nd District'),
('AZ', 3, 'Arizona 3rd District'),
('AZ', 4, 'Arizona 4th District'),
('AZ', 5, 'Arizona 5th District'),
('AZ', 6, 'Arizona 6th District'),
('AZ', 7, 'Arizona 7th District'),
('AZ', 8, 'Arizona 8th District'),
('AZ', 9, 'Arizona 9th District'),
-- Arkansas
('AR', 1, 'Arkansas 1st District'),
('AR', 2, 'Arkansas 2nd District'),
('AR', 3, 'Arkansas 3rd District'),
('AR', 4, 'Arkansas 4th District'),
-- American Samoa
('AS', 0, 'American Samoa Delegate'),
-- California (52 districts)
('CA', 1, 'California 1st District'),
('CA', 2, 'California 2nd District'),
('CA', 3, 'California 3rd District'),
('CA', 4, 'California 4th District'),
('CA', 5, 'California 5th District'),
('CA', 6, 'California 6th District'),
('CA', 7, 'California 7th District'),
('CA', 8, 'California 8th District'),
('CA', 9, 'California 9th District'),
('CA', 10, 'California 10th District'),
('CA', 11, 'California 11th District'),
('CA', 12, 'California 12th District'),
('CA', 13, 'California 13th District'),
('CA', 14, 'California 14th District'),
('CA', 15, 'California 15th District'),
('CA', 16, 'California 16th District'),
('CA', 17, 'California 17th District'),
('CA', 18, 'California 18th District'),
('CA', 19, 'California 19th District'),
('CA', 20, 'California 20th District'),
('CA', 21, 'California 21st District'),
('CA', 22, 'California 22nd District'),
('CA', 23, 'California 23rd District'),
('CA', 24, 'California 24th District'),
('CA', 25, 'California 25th District'),
('CA', 26, 'California 26th District'),
('CA', 27, 'California 27th District'),
('CA', 28, 'California 28th District'),
('CA', 29, 'California 29th District'),
('CA', 30, 'California 30th District'),
('CA', 31, 'California 31st District'),
('CA', 32, 'California 32nd District'),
('CA', 33, 'California 33rd District'),
('CA', 34, 'California 34th District'),
('CA', 35, 'California 35th District'),
('CA', 36, 'California 36th District'),
('CA', 37, 'California 37th District'),
('CA', 38, 'California 38th District'),
('CA', 39, 'California 39th District'),
('CA', 40, 'California 40th District'),
('CA', 41, 'California 41st District'),
('CA', 42, 'California 42nd District'),
('CA', 43, 'California 43rd District'),
('CA', 44, 'California 44th District'),
('CA', 45, 'California 45th District'),
('CA', 46, 'California 46th District'),
('CA', 47, 'California 47th District'),
('CA', 48, 'California 48th District'),
('CA', 49, 'California 49th District'),
('CA', 50, 'California 50th District'),
('CA', 51, 'California 51st District'),
('CA', 52, 'California 52nd District'),
-- Colorado
('CO', 1, 'Colorado 1st District'),
('CO', 2, 'Colorado 2nd District'),
('CO', 3, 'Colorado 3rd District'),
('CO', 4, 'Colorado 4th District'),
('CO', 5, 'Colorado 5th District'),
('CO', 6, 'Colorado 6th District'),
('CO', 7, 'Colorado 7th District'),
('CO', 8, 'Colorado 8th District'),
-- Connecticut
('CT', 1, 'Connecticut 1st District'),
('CT', 2, 'Connecticut 2nd District'),
('CT', 3, 'Connecticut 3rd District'),
('CT', 4, 'Connecticut 4th District'),
('CT', 5, 'Connecticut 5th District'),
-- Delaware
('DE', 0, 'Delaware At-Large'),
-- District of Columbia
('DC', 0, 'District of Columbia Delegate'),
-- Florida
('FL', 1, 'Florida 1st District'),
('FL', 2, 'Florida 2nd District'),
('FL', 3, 'Florida 3rd District'),
('FL', 4, 'Florida 4th District'),
('FL', 5, 'Florida 5th District'),
('FL', 6, 'Florida 6th District'),
('FL', 7, 'Florida 7th District'),
('FL', 8, 'Florida 8th District'),
('FL', 9, 'Florida 9th District'),
('FL', 10, 'Florida 10th District'),
('FL', 11, 'Florida 11th District'),
('FL', 12, 'Florida 12th District'),
('FL', 13, 'Florida 13th District'),
('FL', 14, 'Florida 14th District'),
('FL', 15, 'Florida 15th District'),
('FL', 16, 'Florida 16th District'),
('FL', 17, 'Florida 17th District'),
('FL', 18, 'Florida 18th District'),
('FL', 19, 'Florida 19th District'),
('FL', 20, 'Florida 20th District'),
('FL', 21, 'Florida 21st District'),
('FL', 22, 'Florida 22nd District'),
('FL', 23, 'Florida 23rd District'),
('FL', 24, 'Florida 24th District'),
('FL', 25, 'Florida 25th District'),
('FL', 26, 'Florida 26th District'),
('FL', 27, 'Florida 27th District'),
('FL', 28, 'Florida 28th District')
ON CONFLICT(state_code, district_number) DO NOTHING;